import type { Doctor, Team, Shift, LeaveDay, NationalHoliday } from '@/types/scheduling';

// Fixed sample month — November 2025. Hardcoded so server and client renders match
// (no `new Date()` at module load → no hydration mismatch).
export const DEMO_YEAR = 2025;
export const DEMO_MONTH = 10; // 0-indexed: November
export const DEMO_DAYS_IN_MONTH = 30;
export const DEMO_BASE_NORM_HOURS = 140; // 7h × 20 working days in Nov 2025

export const demoTeams: Team[] = [
  { id: 'demo-team-1', name: 'Echipa 1', color: '#0F6E56', order: 1 },
  { id: 'demo-team-2', name: 'Echipa 2', color: '#1D9E75', order: 2 },
  { id: 'demo-team-3', name: 'Echipa 3', color: '#0A3D31', order: 3 },
  { id: 'demo-team-4', name: 'Echipa 4', color: '#2BB088', order: 4 },
];

export const demoDoctors: Doctor[] = [
  { id: 'demo-doc-1', name: 'Dr. Ana Popescu',      team_id: 'demo-team-1', is_floating: false, display_order: 1, preferences: {} },
  { id: 'demo-doc-2', name: 'Dr. Mihai Ionescu',    team_id: 'demo-team-2', is_floating: false, display_order: 2, preferences: {} },
  { id: 'demo-doc-3', name: 'Dr. Elena Dumitrescu', team_id: 'demo-team-3', is_floating: false, display_order: 3, preferences: {} },
  { id: 'demo-doc-4', name: 'Dr. Andrei Marin',     team_id: 'demo-team-4', is_floating: false, display_order: 4, preferences: {} },
  { id: 'demo-doc-5', name: 'Dr. Cristina Stoica',  team_id: 'demo-team-1', is_floating: true, is_optional: true, display_order: 5, preferences: {} },
];

// Per-doctor shift plan, generated by running SchedulingEngine over this exact config
// (4 teams × 1 doctor + 1 floating optional, shiftsPerDay=1, shiftsPerNight=1, Nov 2025,
//  Dr. Elena leave Nov 12-14, Sf. Andrei holiday Nov 30). See _local/gen-demo-schedule.ts.
const demoShiftPlan: Record<string, ReadonlyArray<[number, 'day' | 'night']>> = {
  'demo-doc-1': [[1, 'day'], [2, 'night'], [5, 'day'], [6, 'night'], [9, 'day'], [10, 'night'], [13, 'day'], [14, 'night'], [17, 'day'], [18, 'night'], [21, 'day'], [22, 'night'], [25, 'day'], [26, 'night'], [29, 'day'], [30, 'night']],
  'demo-doc-2': [[2, 'day'], [3, 'night'], [6, 'day'], [7, 'night'], [10, 'day'], [11, 'night'], [14, 'day'], [15, 'night'], [18, 'day'], [19, 'night'], [22, 'day'], [23, 'night'], [26, 'day'], [27, 'night'], [30, 'day']],
  'demo-doc-3': [[3, 'day'], [4, 'night'], [7, 'day'], [8, 'night'], [11, 'day'], [15, 'day'], [16, 'night'], [19, 'day'], [20, 'night'], [23, 'day'], [24, 'night'], [27, 'day'], [28, 'night']],
  'demo-doc-4': [[1, 'night'], [4, 'day'], [5, 'night'], [8, 'day'], [9, 'night'], [12, 'day'], [13, 'night'], [16, 'day'], [17, 'night'], [20, 'day'], [21, 'night'], [24, 'day'], [25, 'night'], [28, 'day'], [29, 'night']],
  'demo-doc-5': [[12, 'night']],
};

const pad = (n: number) => String(n).padStart(2, '0');
const dateStr = (day: number) => `${DEMO_YEAR}-${pad(DEMO_MONTH + 1)}-${pad(day)}`;

const buildShifts = (): Shift[] => {
  const out: Shift[] = [];
  for (const [doctorId, entries] of Object.entries(demoShiftPlan)) {
    for (const [day, type] of entries) {
      out.push({
        id: `demo-shift-${doctorId}-${dateStr(day)}-${type}`,
        doctor_id: doctorId,
        shift_date: dateStr(day),
        shift_type: type,
        // Mark one Dr. Ana shift as a manual override so the yellow ring shows in the demo.
        is_manual: doctorId === 'demo-doc-1' && day === 17 && type === 'day',
      });
    }
  }
  return out;
};

export const demoShifts: Shift[] = buildShifts();

export const demoLeaveDays: LeaveDay[] = [
  // Dr. Elena takes regular leave Nov 12-14 (Wed-Fri).
  { id: 'demo-leave-doc3-nov12', doctor_id: 'demo-doc-3', leave_date: dateStr(12), leave_type: 'regular' },
  { id: 'demo-leave-doc3-nov13', doctor_id: 'demo-doc-3', leave_date: dateStr(13), leave_type: 'regular' },
  { id: 'demo-leave-doc3-nov14', doctor_id: 'demo-doc-3', leave_date: dateStr(14), leave_type: 'regular' },
];

export const demoNationalHolidays: NationalHoliday[] = [
  // Sf. Andrei — RO national holiday.
  { id: 'demo-holiday-nov30', holiday_date: dateStr(30), description: 'Sf. Andrei' },
];

// Precomputed per-doctor stats matching the ShiftGridDoctorRow `DoctorStats` shape.
export const demoDoctorStats: Record<string, { dayShifts: number; nightShifts: number; totalHours: number; baseNorm: number }> =
  Object.fromEntries(
    demoDoctors.map((d) => {
      const docShifts = demoShifts.filter((s) => s.doctor_id === d.id);
      const dayShifts = docShifts.filter((s) => s.shift_type === 'day').length;
      const nightShifts = docShifts.filter((s) => s.shift_type === 'night').length;
      return [
        d.id,
        {
          dayShifts,
          nightShifts,
          totalHours: (dayShifts + nightShifts) * 12,
          baseNorm: d.is_optional ? 0 : DEMO_BASE_NORM_HOURS,
        },
      ];
    })
  );
