'use client';

import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check, CheckCircle2, Users, Zap, CalendarDays } from 'lucide-react';
import { useTranslation } from '@/lib/i18n';

export default function MarketingV1() {
  const { t } = useTranslation();

  return (
    <>
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-white dark:bg-gray-950">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-50 via-white to-indigo-50 dark:from-gray-950 dark:via-gray-900 dark:to-gray-950 opacity-80" />
        <div className="relative pt-20 pb-12 sm:pt-28 sm:pb-16">
          <div className="container mx-auto px-4">
            <div className="text-center max-w-3xl mx-auto">
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 dark:text-white mb-6 tracking-tight leading-tight">
                {t('marketing.hero.v1.headline')}{' '}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">
                  {t('marketing.hero.v1.headlineAccent')}
                </span>
              </h1>

              <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 mb-10 max-w-2xl mx-auto leading-relaxed">
                {t('marketing.hero.v1.subheadline')}
              </p>

              <Link
                href="/sign-in"
                className="inline-flex items-center px-8 py-4 text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors text-lg font-medium shadow-lg shadow-blue-600/25"
              >
                {t('marketing.hero.v1.cta')}
                <ArrowRight className="ml-2 w-5 h-5" />
              </Link>

              <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-6 text-sm text-gray-600 dark:text-gray-400">
                {[t('marketing.hero.v1.check1'), t('marketing.hero.v1.check2'), t('marketing.hero.v1.check3')].map((text) => (
                  <div key={text} className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-green-500 flex-shrink-0" />
                    <span>{text}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Demo Screenshot 1 — Grid */}
      <section className="pb-16 sm:pb-24 bg-white dark:bg-gray-950">
        <div className="container mx-auto px-4">
          <div className="relative -mt-4 max-w-5xl mx-auto">
            <div className="rounded-xl overflow-hidden shadow-2xl border border-gray-200 dark:border-gray-700">
              <Image
                src="/images/demo1.png"
                alt="PlanGarzi schedule grid"
                width={1200}
                height={700}
                className="w-full h-auto"
                priority
              />
            </div>
            <p className="text-center text-sm text-gray-500 dark:text-gray-400 mt-4">
              {t('marketing.demo.gridCaption')}
            </p>
          </div>
        </div>
      </section>

      {/* Features Section — 3 Cards */}
      <section className="py-16 sm:py-24 bg-gray-50 dark:bg-gray-900">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            {[
              { icon: <Users className="w-6 h-6" />, title: t('marketing.features.configureTeams'), desc: t('marketing.features.configureTeamsDesc') },
              { icon: <Zap className="w-6 h-6" />, title: t('marketing.features.autoGenerate'), desc: t('marketing.features.autoGenerateDesc') },
              { icon: <CalendarDays className="w-6 h-6" />, title: t('marketing.features.reviewAdjust'), desc: t('marketing.features.reviewAdjustDesc') },
            ].map((f) => (
              <div key={f.title} className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm border border-gray-100 dark:border-gray-700 hover:shadow-md transition-shadow">
                <div className="text-blue-600 mb-4">{f.icon}</div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">{f.title}</h3>
                <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Demo Screenshot 2 — Config */}
      <section className="py-16 sm:py-24 bg-white dark:bg-gray-950">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto">
            <div className="rounded-xl overflow-hidden shadow-xl border border-gray-200 dark:border-gray-700">
              <Image
                src="/images/demo2.png"
                alt="PlanGarzi team configuration"
                width={1200}
                height={700}
                className="w-full h-auto"
              />
            </div>
            <p className="text-center text-sm text-gray-500 dark:text-gray-400 mt-4">
              {t('marketing.demo.configCaption')}
            </p>
          </div>
        </div>
      </section>

      {/* Feature Checklist */}
      <section className="py-16 sm:py-24 bg-white dark:bg-gray-950">
        <div className="container mx-auto px-4">
          <div className="max-w-2xl mx-auto">
            <ul className="space-y-5">
              {[
                t('marketing.featureList.autoSchedule'),
                t('marketing.featureList.fairDistribution'),
                t('marketing.featureList.leaveManagement'),
                t('marketing.featureList.conflictDetection'),
                t('marketing.featureList.pdfExport'),
                t('marketing.featureList.multiLanguage'),
              ].map((item) => (
                <li key={item} className="flex items-start gap-3">
                  <CheckCircle2 className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700 dark:text-gray-300 text-lg">{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 sm:py-20 bg-gray-50 dark:bg-gray-900">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-6">
            {t('marketing.cta.v1')}
          </h2>
          <Link
            href="/sign-in"
            className="inline-flex items-center px-8 py-4 text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors text-lg font-medium"
          >
            {t('marketing.hero.v1.cta')}
            <ArrowRight className="ml-2 w-5 h-5" />
          </Link>
        </div>
      </section>
    </>
  );
}
